name: HTTP Server
 
on:
 Http:
    path: /webhook
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
    - name: Start HTTP Server
      run: python server.pyKEY }}
 
          
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www
          
          # sftp args
          args: '-o ConnectTimeout=5'